######################################################################
##
## Filename: omp_test.udo
## Created on: Thu Apr 10 1:46:32 PM Central Daylight Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
